import { colors } from './colors';
import { radius, space } from './space';
import { fontSize } from './typography';

export const cssVariables = `:root {
  --color-accent: ${colors.accent};
  --color-accent-dark: ${colors.accentDark};
  --color-accent-muted: ${colors.accentMuted};
  --color-primary: ${colors.primary};
  --color-primary-light: ${colors.primaryLight};
  --color-primary-dark: ${colors.primaryDark};
  --color-canvas: ${colors.canvas};
  --color-canvas-light: ${colors.canvasLight};
  --color-surface: ${colors.surface};
  --color-surface-dark: ${colors.surfaceDark};
  --color-muted: ${colors.muted};
  --color-border: ${colors.border};
  --color-banner-bg: ${colors.bannerBg};
  --color-banner-border: ${colors.bannerBorder};
  --color-notice-border: ${colors.noticeBorder};
  --color-urgency: ${colors.urgency};
  --color-urgency-bg: ${colors.urgencyBg};
  --color-cta: ${colors.cta};
  --color-text: ${colors.text};
  --color-on-dark: ${colors.onDark};
  --radius-md: ${radius.md};
  --radius-lg: ${radius.lg};
  --radius-full: ${radius.full};
  --font-size-base: ${fontSize.base};
  --space-4: ${space[4]};
  --space-5: ${space[5]};
  --space-6: ${space[6]};
  --space-8: ${space[8]};
}`;
