/**
 * Web checkout chrome styles. Values reference CSS custom properties emitted
 * by `@repo/tokens` `cssVariables` — no local hex. Kept as DOM styles because
 * this shell is SSR HTML (not react-native-web).
 */
export const checkoutPageStyles = {
  main: {
    maxWidth: 1100,
    margin: '0 auto',
    padding: 'var(--space-6) var(--space-5) var(--space-8)',
    lineHeight: 1.5,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'minmax(0, 1.5fr) minmax(280px, 1fr)',
    gap: 'var(--space-5)',
    alignItems: 'start',
  },
  card: {
    backgroundColor: 'var(--color-surface)',
    borderRadius: 'var(--radius-lg)',
    padding: 'var(--space-5)',
    border: '1px solid var(--color-border)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 'var(--space-4)',
  },
  summaryAside: {
    backgroundColor: 'var(--color-canvas-light)',
    borderRadius: 'var(--radius-lg)',
    padding: 'var(--space-4)',
    border: '1px solid var(--color-border)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 'var(--space-4)',
  },
  summaryCard: {
    backgroundColor: 'var(--color-surface)',
    borderRadius: 'var(--radius-lg)',
    padding: 'var(--space-4)',
    border: '1px solid var(--color-border)',
    display: 'flex',
    flexDirection: 'column' as const,
    gap: 'var(--space-3)',
  },
  contactRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 'var(--space-3)',
    paddingBottom: 'var(--space-3)',
    borderBottom: '1px solid var(--color-border)',
  },
  contactLabel: {
    margin: 0,
    fontSize: '1.125rem',
    fontWeight: 700,
  },
  contactEmail: {
    margin: 0,
    color: 'var(--color-muted)',
    fontSize: '0.9375rem',
  },
  map: {
    position: 'relative' as const,
    height: 220,
    borderRadius: 'var(--radius-lg)',
    overflow: 'hidden',
    backgroundColor: 'var(--color-stadium-map-bg)',
    border: '1px solid var(--color-border)',
  },
  mapImage: {
    display: 'block',
    width: '100%',
    height: '100%',
    objectFit: 'cover' as const,
  },
  mapBubble: {
    position: 'absolute' as const,
    transform: 'translate(-50%, -50%)',
    padding: '4px 10px',
    borderRadius: 'var(--radius-full)',
    backgroundColor: 'var(--color-accent)',
    border: '2px solid var(--color-link)',
    fontSize: 12,
    fontWeight: 700,
  },
  venueLine: {
    margin: 0,
    color: 'var(--color-muted)',
    fontSize: '0.75rem',
    fontWeight: 600,
    letterSpacing: '0.04em',
    textTransform: 'uppercase' as const,
  },
  artist: {
    margin: 0,
    fontSize: '1.25rem',
    fontWeight: 700,
  },
  meta: {
    margin: 0,
    fontSize: '0.9375rem',
  },
  muted: {
    margin: 0,
    color: 'var(--color-muted)',
    fontSize: '0.875rem',
  },
  urgency: {
    padding: '0.5rem 0.75rem',
    borderRadius: 'var(--radius-md)',
    backgroundColor: 'var(--color-urgency-bg)',
    border: '1px solid var(--color-urgency-border)',
    textAlign: 'center' as const,
    fontSize: '0.875rem',
    fontWeight: 600,
  },
  priceRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 'var(--space-3)',
    margin: 0,
  },
  promo: {
    margin: 0,
    color: 'var(--color-link)',
    fontSize: '0.875rem',
    fontWeight: 600,
    textDecoration: 'underline',
  },
  totalLabel: {
    margin: 0,
    fontSize: '1.125rem',
    fontWeight: 700,
  },
  totalValue: {
    margin: 0,
    fontSize: '1.125rem',
    fontWeight: 700,
  },
  deal: {
    padding: 'var(--space-4)',
    borderRadius: 'var(--radius-lg)',
    backgroundColor: 'var(--color-accent-muted)',
    color: 'var(--color-accent-dark)',
    fontSize: '0.875rem',
  },
  dealTitle: {
    margin: '0 0 0.35rem',
    fontWeight: 700,
    fontSize: '1rem',
  },
  dealBody: {
    margin: 0,
  },
  guarantee: {
    display: 'flex',
    alignItems: 'center',
    gap: 'var(--space-4)',
    padding: 'var(--space-4)',
    borderRadius: 'var(--radius-lg)',
    backgroundColor: 'var(--color-canvas-light)',
    border: '1px solid var(--color-border)',
  },
  guaranteeCopy: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column' as const,
    gap: '0.35rem',
  },
  guaranteeTitle: {
    margin: 0,
    fontSize: '1rem',
    fontWeight: 700,
  },
  guaranteeItem: {
    margin: 0,
    fontSize: '0.875rem',
  },
  guaranteeShield: {
    width: 56,
    height: 64,
    borderRadius: 'var(--radius-lg)',
    backgroundColor: 'var(--color-guarantee)',
    color: 'var(--color-on-dark)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '1.5rem',
    fontWeight: 800,
    flexShrink: 0,
  },
  id: { color: 'var(--color-muted)', fontSize: '0.8125rem', margin: 0 },
  failure: {
    backgroundColor: 'var(--color-surface)',
    borderRadius: 'var(--radius-lg)',
    padding: 'var(--space-6)',
    border: '1px solid var(--color-border)',
    maxWidth: 520,
  },
} as const;
